kind: ImageStream
apiVersion: image.openshift.io/v1

metadata:
  name: ecopaths
  labels:
    app: ecopaths
spec:
  lookupPolicy:
    local: false
  tags:
    - name: staging
      from:
        kind: DockerImage
        name: uyenmh/ecopaths:staging
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Local
